apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - service.yaml
  - secret.yaml
  - uwsgi.yaml
{%- if cookiecutter.use_celery.lower() == 'y' %}
  - worker.yaml
  - beat.yaml
{%- endif %}
{%- if cookiecutter.web_express.lower() == 'y' %}
  - express.yaml
{%- endif %}