apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_name.lower()}}-uwsgi
  labels:
    app: {{cookiecutter.project_name.lower()}}-uwsgi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.project_name.lower()}}-uwsgi
  template:
    metadata:
      labels:
        app: {{cookiecutter.project_name.lower()}}-uwsgi
    spec:
      containers:
        - name: {{cookiecutter.project_name.lower()}}-uwsgi
          image: {{cookiecutter.registry}}{{cookiecutter.project_name.lower()}}:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http-8000
          env:
            - name: EXEC_CMD
              value: uwsgi
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 10Mi
      imagePullSecrets:
        - name: registry-authentication