apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: pro-
resources:
  - ../../base
patchesStrategicMerge:
  - uwsgi.yaml
{%- if cookiecutter.use_celery.lower() == 'y' %}
  - worker.yaml
  - beat.yaml
{%- endif %}
  - service.yaml
{%- if cookiecutter.web_express.lower() == 'y' %}
  - express.yaml
{%- endif %}
images:
  - name: {{cookiecutter.registry}}{{cookiecutter.project_name.lower()}}
    newTag: master
{%- if cookiecutter.web_express.lower() == 'y' %}
  - name: {{cookiecutter.registry}}{{cookiecutter.project_name.lower()}}-web
    newTag: master
{%- endif %}
configMapGenerator:
  - name: envs
    envs:
      - envs.yaml