apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_name.lower()}}-uwsgi
  annotations:
    kubesphere.io/description: {{cookiecutter.project_name.lower()}} backend uwsgi in production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.project_name.lower()}}-uwsgi
  template:
    spec:
      containers:
        - name: {{cookiecutter.project_name.lower()}}-uwsgi
          env:
            - name: RUN_ENV
              value: PRODUCT
          envFrom:
            - configMapRef:
                name: envs
