apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_name.lower()}}-worker
  annotations:
    kubesphere.io/description: {{cookiecutter.project_name.lower()}} frontend celery worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.project_name.lower()}}-worker
  template:
    spec:
      containers:
        - name: {{cookiecutter.project_name.lower()}}-worker
          env:
            - name: RUN_ENV
              value: PRODUCT
          envFrom:
            - configMapRef:
                name: envs
